version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: linkernetworks

  adminer:
    image: adminer
    restart: always
    ports:
      - 9898:8080