"""New Migration

Revision ID: 106e08d3b34d
Revises: 9b79aaff1647
Create Date: 2021-12-16 04:09:33.768184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106e08d3b34d'
down_revision = '9b79aaff1647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
