"""New Migration

Revision ID: 9b79aaff1647
Revises: c17741cb4073
Create Date: 2021-12-16 04:07:44.927337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b79aaff1647'
down_revision = 'c17741cb4073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
