"""New Migration

Revision ID: a69860e0ce6d
Revises: d486f301a53b
Create Date: 2021-12-16 03:41:06.069814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69860e0ce6d'
down_revision = 'd486f301a53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
