"""New Migration

Revision ID: d486f301a53b
Revises: ca2e8bee7fb3
Create Date: 2021-12-15 10:49:09.551740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd486f301a53b'
down_revision = 'ca2e8bee7fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
