"""New Migration

Revision ID: df31af98a675
Revises: 106e08d3b34d
Create Date: 2021-12-16 04:10:23.663851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df31af98a675'
down_revision = '106e08d3b34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
